import os, pathlib
Q=chr(39);DQ=chr(34);NL=chr(10);LT=chr(60);GT=chr(62)
base=r"c:\art therapy app\client\src"
def w(rel,*L):
    p=os.path.join(base,rel.replace("/",os.sep))
    pathlib.Path(p).parent.mkdir(parents=True,exist_ok=True)
    open(p,"w",encoding="utf-8",newline="\n").write(NL.join(L)+NL)
    print("OK",p)
HBE="HTML"+"Button"+"Element"
HIE="HTML"+"Input"+"Element"
HTAE="HTML"+"Text"+"Area"+"Element"
HSE="HTML"+"Select"+"Element"
FWR="React."+"forwardRef"
BP="Button"+"Props"
IP="Input"+"Props"
TP="Textarea"+"Props"
SP="Select"+"Props"
BFWR=FWR+LT+HBE+", "+BP+GT
IFWR=FWR+LT+HIE+", "+IP+GT
TFWR=FWR+LT+HTAE+", "+TP+GT
SFWR=FWR+LT+HSE+", "+SP+GT
w("components/ui/Button.tsx",
  "import React from "+Q+"react"+Q+";",
  "import { cn } from "+Q+"../../utils/cn"+Q+";",
  "",
  "type Variant = "+Q+"primary"+Q+" | "+Q+"secondary"+Q+" | "+Q+"outline"+Q+" | "+Q+"ghost"+Q+" | "+Q+"danger"+Q+";",
  "type Size = "+Q+"sm"+Q+" | "+Q+"md"+Q+" | "+Q+"lg"+Q+";",
  "",
  "interface "+BP+" extends React."+"Button"+"HTML"+"Attributes"+LT+HBE+GT+" {",
  "  variant?: Variant;","  size?: Size;","  loading?: boolean;","  children: React.ReactNode;","}","",
  "const variantClasses: Record"+LT+"Variant, string"+GT+" = {",
  "  primary:   "+Q+"bg-teal-600 text-white hover:bg-teal-700 focus-visible:ring-teal-500"+Q+",",
  "  secondary: "+Q+"bg-stone-800 text-white hover:bg-stone-900 focus-visible:ring-stone-500"+Q+",",
  "  outline:   "+Q+"border border-stone-300 text-stone-700 bg-white hover:bg-stone-50 focus-visible:ring-stone-400"+Q+",",
  "  ghost:     "+Q+"text-stone-600 hover:bg-stone-100 hover:text-stone-900 focus-visible:ring-stone-400"+Q+",",
  "  danger:    "+Q+"bg-rose-600 text-white hover:bg-rose-700 focus-visible:ring-rose-500"+Q+",",
  "};","",
  "const sizeClasses: Record"+LT+"Size, string"+GT+" = {",
  "  sm: "+Q+"h-8 px-3 text-sm rounded-md gap-1.5"+Q+",",
  "  md: "+Q+"h-10 px-4 text-sm rounded-lg gap-2"+Q+",",
  "  lg: "+Q+"h-12 px-6 text-base rounded-lg gap-2"+Q+",",
  "};","",
  "export const Button = "+BFWR+"(",
  "  ({ variant = "+Q+"primary"+Q+", size = "+Q+"md"+Q+", loading = false, className, disabled, children, ...props }, ref) => (",
  "    "+LT+"button","      ref={ref}","      disabled={disabled || loading}","      className={cn(",
  "        "+Q+"inline-flex items-center justify-center font-medium transition-colors"+Q+",",
  "        "+Q+"focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2"+Q+",",
  "        "+Q+"disabled:pointer-events-none disabled:opacity-50"+Q+",",
  "        variantClasses[variant],","        sizeClasses[size],","        className","      )}","      {...props}","    >",
  "      {loading && (",
  "        "+LT+"svg className="+DQ+"animate-spin h-4 w-4 shrink-0"+DQ+" viewBox="+DQ+"0 0 24 24"+DQ+" fill="+DQ+"none"+DQ+GT,
  "          "+LT+"circle className="+DQ+"opacity-25"+DQ+" cx="+DQ+"12"+DQ+" cy="+DQ+"12"+DQ+" r="+DQ+"10"+DQ+" stroke="+DQ+"currentColor"+DQ+" strokeWidth="+DQ+"4"+DQ+" /"+GT,
  "          "+LT+"path className="+DQ+"opacity-75"+DQ+" fill="+DQ+"currentColor"+DQ+" d="+DQ+"M4 12a8 8 0 018-8v8H4z"+DQ+" /"+GT,
  "        "+LT+"/svg"+GT,"      )}","      {children}","    "+LT+"/button"+GT,"  )",");",
  "Button.displayName = "+Q+"Button"+Q+";",
)
w("components/ui/Input.tsx",
  "import React from "+Q+"react"+Q+";",
  "import { cn } from "+Q+"../../utils/cn"+Q+";",
  "",
  "interface "+IP+" extends React."+"Input"+"HTML"+"Attributes"+LT+HIE+GT+" {",
  "  label?: string;","  error?: string;","  hint?: string;","}","",
  "export const Input = "+IFWR+"(",
  "  ({ label, error, hint, className, id, ...props }, ref) => {",
  "    const inputId = id ?? label?.toLowerCase().replace(/\\s+/g, "+Q+"-"+Q+");",
  "    return (",
  "      <div className="+DQ+"flex flex-col gap-1"+DQ+">",
  "        {label && (",
  "          <label htmlFor={inputId} className="+DQ+"text-sm font-medium text-stone-700"+DQ+">",
  "            {label}","          </label>","        )}",
  "        <input","          ref={ref}","          id={inputId}","          className={cn(",
  "            "+Q+"h-10 w-full rounded-lg border bg-white px-3 text-sm text-stone-900"+Q+",",
  "            "+Q+"placeholder:text-stone-400 transition-colors"+Q+",",
  "            "+Q+"focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500"+Q+",",
  "            error ? "+Q+"border-rose-400 focus:ring-rose-400"+Q+" : "+Q+"border-stone-300"+Q+",",
  "            className","          )}","          {...props}","        />",
  "        {error && <p className="+DQ+"text-xs text-rose-500"+DQ+">{error}</p>}",
  "        {hint && !error && <p className="+DQ+"text-xs text-stone-500"+DQ+">{hint}</p>}",
  "      </div>","    );","  }",");",
  "Input.displayName = "+Q+"Input"+Q+";",
)
w("components/ui/Textarea.tsx",
  "import React from "+Q+"react"+Q+";",
  "import { cn } from "+Q+"../../utils/cn"+Q+";",
  "",
  "interface "+TP+" extends React."+"Textarea"+"HTML"+"Attributes"+LT+HTAE+GT+" {",
  "  label?: string;","  error?: string;","  hint?: string;","}","",
  "export const Textarea = "+TFWR+"(",
  "  ({ label, error, hint, className, id, ...props }, ref) => {",
  "    const textareaId = id ?? label?.toLowerCase().replace(/\\s+/g, "+Q+"-"+Q+");",
  "    return (",
  "      <div className="+DQ+"flex flex-col gap-1"+DQ+">",
  "        {label && (",
  "          <label htmlFor={textareaId} className="+DQ+"text-sm font-medium text-stone-700"+DQ+">",
  "            {label}","          </label>","        )}",
  "        <textarea","          ref={ref}","          id={textareaId}","          className={cn(",
  "            "+Q+"w-full rounded-lg border bg-white px-3 py-2 text-sm text-stone-900"+Q+",",
  "            "+Q+"placeholder:text-stone-400 transition-colors resize-none"+Q+",",
  "            "+Q+"focus:outline-none focus:ring-2 focus:ring-teal-500 focus:border-teal-500"+Q+",",
  "            error ? "+Q+"border-rose-400 focus:ring-rose-400"+Q+" : "+Q+"border-stone-300"+Q+",",
  "            className","          )}","          {...props}","        />",
  "        {error && <p className="+DQ+"text-xs text-rose-500"+DQ+">{error}</p>}",
  "        {hint && !error && <p className="+DQ+"text-xs text-stone-500"+DQ+">{hint}</p>}",
  "      </div>","    );","  }",");",
  "Textarea.displayName = "+Q+"Textarea"+Q+";",
)
w("components/ui/Card.tsx",
  "import React from "+Q+"react"+Q+";",
  "import { cn } from "+Q+"../../utils/cn"+Q+";",
  "",
  "interface CardProps extends React."+"HTML"+"Attributes"+LT+"HTMLDivElement"+GT+" {",
  "  children: React.ReactNode;","}","",
  "export const Card = ({ className, children, ...props }: CardProps) => (",
  "  <div",
  "    className={cn("+Q+"rounded-xl border border-stone-200 bg-white shadow-sm"+Q+", className)}",
  "    {...props}","  >","    {children}","  </div>",");","",
  "export const CardHeader = ({ className, children, ...props }: CardProps) => (",
  "  <div className={cn("+Q+"p-6 pb-0"+Q+", className)} {...props}>{children}</div>",");","",
  "export const CardTitle = ({ className, children, ...props }: CardProps) => (",
  "  <h3 className={cn("+Q+"text-lg font-semibold text-stone-900"+Q+", className)} {...props}>{children}</h3>",");","",
  "export const CardDescription = ({ className, children, ...props }: CardProps) => (",
  "  <p className={cn("+Q+"text-sm text-stone-500 mt-1"+Q+", className)} {...props}>{children}</p>",");","",
  "export const CardContent = ({ className, children, ...props }: CardProps) => (",
  "  <div className={cn("+Q+"p-6"+Q+", className)} {...props}>{children}</div>",");","",
  "export const CardFooter = ({ className, children, ...props }: CardProps) => (",
  "  <div className={cn("+Q+"p-6 pt-0 flex items-center"+Q+", className)} {...props}>{children}</div>",");",
)
w("components/ui/Badge.tsx",
  "import React from "+Q+"react"+Q+";",
  "import { cn } from "+Q+"../../utils/cn"+Q+";",
  "",
  "type BadgeVariant = "+Q+"default"+Q+" | "+Q+"success"+Q+" | "+Q+"warning"+Q+" | "+Q+"danger"+Q+" | "+Q+"info"+Q+" | "+Q+"outline"+Q+";",
  "",
  "interface BadgeProps extends React."+"HTML"+"Attributes"+LT+"HTMLSpanElement"+GT+" {",
  "  variant?: BadgeVariant;","}","",
  "const variantMap: Record"+LT+"BadgeVariant, string"+GT+" = {",
  "  default: "+Q+"bg-stone-100 text-stone-700"+Q+",",
  "  success: "+Q+"bg-emerald-100 text-emerald-700"+Q+",",
  "  warning: "+Q+"bg-amber-100 text-amber-700"+Q+",",
  "  danger:  "+Q+"bg-rose-100 text-rose-700"+Q+",",
  "  info:    "+Q+"bg-teal-100 text-teal-700"+Q+",",
  "  outline: "+Q+"border border-stone-300 text-stone-600 bg-transparent"+Q+",",
  "};","",
  "export const Badge = ({ variant = "+Q+"default"+Q+", className, children, ...props }: BadgeProps) => (",
  "  <span",
  "    className={cn(",
  "      "+Q+"inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium"+Q+",",
