import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Calendar } from 'lucide-react';
import { Input } from '../ui/Input';
import { DatePicker } from '../ui/DatePicker';
import type { TherapyPlanEvent } from '../../types';
import type { TherapyPlanEventPayload } from '../../api/therapyPlans';

// ─── Draft type (used in edit mode) ──────────────────────────────────────────

export interface PlanEventDraft {
  /** Stable React key — client-side only, never sent to the API. */
  localId: string;
  /** "YYYY-MM-DDTHH:MM" format for datetime-local inputs. */
  startTime: string;
  endTime: string;
  title: string;
  isAvailable: boolean;
  order: number;
}

// ─── Helpers (exported for use in CreateTherapyPlan / EditTherapyPlan) ────────

const toDatetimeLocal = (iso?: string | null): string => {
  if (!iso) return '';
  return iso.slice(0, 16);
};

export const eventsToFormDrafts = (events: TherapyPlanEvent[]): PlanEventDraft[] =>
  [...events]
    .sort((a, b) => a.order - b.order)
    .map((e, idx) => ({
      localId: e.id,
      startTime: toDatetimeLocal(e.startTime),
      endTime: toDatetimeLocal(e.endTime),
      title: e.title ?? `Day ${idx + 1}`,
      isAvailable: e.isAvailable,
      order: idx,
    }));

export const draftsToApiPayload = (drafts: PlanEventDraft[]): TherapyPlanEventPayload[] =>
  drafts.map((d, idx) => ({
    startTime: new Date(d.startTime).toISOString(),
    endTime: d.endTime ? new Date(d.endTime).toISOString() : null,
    title: d.title.trim() || null,
    isAvailable: d.isAvailable,
    order: idx,
  }));

// ─── Auto-generation for WELLNESS_RETREAT ────────────────────────────────────

function autoGenerateDays(
  planStartTime: string,
  n: number,
  existing: PlanEventDraft[],
): PlanEventDraft[] {
  if (!planStartTime) return [];
  const base = new Date(planStartTime);
  if (isNaN(base.getTime())) return [];

  const baseTimeHHMM = planStartTime.slice(11, 16) || '09:00';

  return Array.from({ length: n }, (_, i) => {
    const d = new Date(base);
    d.setDate(d.getDate() + i);
    const datePrefix = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

    const existingDayDate = existing[i]?.startTime.slice(0, 10);
    const timeHHMM =
      existingDayDate === datePrefix
        ? existing[i].startTime.slice(11, 16) || baseTimeHHMM
        : baseTimeHHMM;

    const existingEndTime =
      existingDayDate === datePrefix ? existing[i].endTime : '';

    return {
      localId: existing[i]?.localId ?? `day-${i}-${Date.now()}-${Math.random()}`,
      startTime: `${datePrefix}T${timeHHMM}`,
      endTime: existingEndTime,
      title: `Day ${i + 1}`,
      isAvailable: true,
      order: i,
    };
  });
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface ViewProps {
  mode: 'view';
  events: TherapyPlanEvent[];
  planType: string;
}

interface EditProps {
  mode: 'edit';
  drafts: PlanEventDraft[];
  planType: string;
  /** "YYYY-MM-DDTHH:MM" from the parent form — drives auto-generation for WELLNESS_RETREAT */
  planStartTime?: string;
  onChange: (drafts: PlanEventDraft[]) => void;
}

type PlanScheduleProps = ViewProps | EditProps;

// ─── Component ────────────────────────────────────────────────────────────────

export const PlanSchedule = (props: PlanScheduleProps) => {
  const { t } = useTranslation();

  // ── VIEW MODE ──────────────────────────────────────────────────────────────

  if (props.mode === 'view') {
    const { events } = props;
    if (!events || events.length === 0) return null;

    const sorted = [...events].sort((a, b) => a.order - b.order);

    return (
      <section className="mb-6">
        <h3 className="text-sm font-medium text-stone-500 uppercase tracking-wide mb-3">
          {t('therapyPlans.schedule.title', 'Schedule')}
        </h3>
        <div className="space-y-2">
          {sorted.map((evt) => (
            <div
              key={evt.id}
              className="flex items-start gap-3 rounded-lg p-3 border bg-stone-50 border-stone-100"
            >
              <Calendar className="h-4 w-4 text-teal-600 flex-shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5">
                  {evt.title && (
                    <span className="text-xs font-semibold text-stone-700 uppercase tracking-wide">
                      {evt.title}
                    </span>
                  )}
                  <span className="text-sm font-medium text-stone-800">
                    {new Date(evt.startTime).toLocaleString()}
                  </span>
                  {evt.endTime && (
                    <span className="text-xs text-stone-500">
                      — {new Date(evt.endTime).toLocaleString()}
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    );
  }

  // ── EDIT MODE — only rendered for WELLNESS_RETREAT ────────────────────────

  if (props.planType !== 'WELLNESS_RETREAT') return null;

  return <WellnessRetreatSchedule {...props} t={t} />;
};

// ─── Separated retreat component (avoids Rules-of-Hooks violations) ───────────

const WellnessRetreatSchedule = ({
  drafts,
  onChange,
  planStartTime,
  t,
}: Omit<EditProps, 'mode' | 'planType'> & { t: ReturnType<typeof useTranslation>['t'] }) => {
  const { i18n } = useTranslation();
  const [numDays, setNumDays] = useState<number>(() => {
    if (drafts.length === 0) return 1;
    if (!planStartTime) return 1;
    const base = new Date(planStartTime);
    const last = new Date(Math.max(...drafts.map(d => new Date(d.startTime).getTime())));
    const diff = Math.ceil((last.getTime() - base.getTime()) / (1000 * 60 * 60 * 24));
    return Math.max(diff + 1, 1);
  });

  const addActivity = (dayIndex: number) => {
    if (!planStartTime) return;
    const base = new Date(planStartTime);
    const dayDate = new Date(base);
    dayDate.setDate(dayDate.getDate() + dayIndex);
    const datePrefix = dayDate.toISOString().split('T')[0];

    const newActivity: PlanEventDraft = {
      localId: `act-${Date.now()}-${Math.random()}`,
      startTime: `${datePrefix}T09:00`,
      endTime: `${datePrefix}T10:00`,
      title: '',
      isAvailable: true,
      order: drafts.length,
    };
    onChange([...drafts, newActivity].sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime()));
  };

  const removeActivity = (localId: string) => {
    onChange(drafts.filter((d) => d.localId !== localId));
  };

  const updateDraft = (localId: string, patch: Partial<PlanEventDraft>) => {
    onChange(drafts.map((d) => (d.localId === localId ? { ...d, ...patch } : d)));
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-stone-100 pb-4">
        <div>
          <h3 className="text-lg font-semibold text-stone-900">{t('therapyPlans.schedule.title', 'Schedule')}</h3>
          <p className="text-base text-stone-500">{t('therapyPlans.schedule.subtitle', 'Plan your daily activities and sessions.')}</p>
        </div>
        <div className="flex items-center gap-3 bg-stone-50 p-2 rounded-lg border border-stone-200">
          <label className="text-xs font-medium text-stone-600 uppercase tracking-wider">
            {t('therapyPlans.schedule.numDays', 'Duration (Days)')}
          </label>
          <input
            type="number"
            min={1}
            max={30}
            value={numDays}
            onChange={(e) => setNumDays(Math.max(1, parseInt(e.target.value) || 1))}
            className="w-14 rounded border border-stone-300 px-2 py-1 text-sm font-semibold text-center focus:outline-none focus:ring-2 focus:ring-teal-500"
          />
        </div>
      </div>

      {!planStartTime && (
        <div className="flex items-center gap-3 p-4 bg-amber-50 rounded-lg border border-amber-100 text-amber-700">
          <Calendar className="h-5 w-5" />
          <p className="text-sm italic">
            {t('therapyPlans.schedule.setStartFirst', 'Please set the primary start date first to begin scheduling.')}
          </p>
        </div>
      )}

      {planStartTime && (
        <div className="space-y-8">
          {Array.from({ length: numDays }, (_, i) => {
            const base = new Date(planStartTime);
            const dayDate = new Date(base);
            dayDate.setDate(dayDate.getDate() + i);
            const dateStr = dayDate.toISOString().split('T')[0];
            const dayActivities = drafts.filter(d => d.startTime.startsWith(dateStr));

            return (
              <div key={`day-${i}`} className="relative pl-6 before:absolute before:left-0 before:top-4 before:bottom-0 before:w-px before:bg-stone-200">
                <div className="absolute left-[-4px] top-1 h-3 w-3 rounded-full bg-teal-500 border-2 border-white" />

                <div className="flex items-center justify-between mb-4">
                  <div>
                    <span className="text-xs font-bold text-teal-600 uppercase mt-1 block">Day {i + 1}</span>
                    <h4 className="text-md font-semibold text-stone-800">
                      {dayDate.toLocaleDateString(i18n.language, { weekday: 'long', month: 'short', day: 'numeric' })}
                    </h4>
                  </div>
                  <button
                    type="button"
                    onClick={() => addActivity(i)}
                    className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-teal-700 bg-teal-50 hover:bg-teal-100 rounded-md transition-colors border border-teal-200"
                  >
                    + {t('therapyPlans.schedule.addActivity', 'Add Activity')}
                  </button>
                </div>

                <div className="space-y-3">
                  {dayActivities.length === 0 ? (
                    <p className="text-sm text-stone-400 italic py-2">{t('therapyPlans.schedule.noActivities', 'No activities planned for this day.')}</p>
                  ) : (
                    dayActivities.map((draft) => (
                      <div
                        key={draft.localId}
                        className="group relative border border-stone-200 rounded-xl p-4 bg-white shadow-sm hover:shadow-md transition-all"
                      >
                        <button
                          type="button"
                          onClick={() => removeActivity(draft.localId)}
                          className="absolute top-3 right-3 p-1.5 text-stone-300 hover:text-rose-500 transition-colors opacity-0 group-hover:opacity-100"
                          title={t('common.remove')}
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                            <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                          </svg>
                        </button>

                        <div className="grid grid-cols-1 gap-4">
                          <input
                            type="text"
                            placeholder={t('therapyPlans.schedule.eventTitlePlaceholder', 'e.g. Morning Meditation')}
                            value={draft.title}
                            onChange={(e) => updateDraft(draft.localId, { title: e.target.value })}
                            className="w-full text-sm font-semibold text-stone-800 placeholder:text-stone-300 border-none p-0 focus:ring-0"
                          />

                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                            <DatePicker
                              label={t('therapyPlans.form.startTime', 'Start Time')}
                              value={draft.startTime}
                              onChange={(val) => updateDraft(draft.localId, { startTime: val })}
                            />
                            <DatePicker
                              label={t('therapyPlans.form.endTime', 'End Time')}
                              value={draft.endTime}
                              onChange={(val) => updateDraft(draft.localId, { endTime: val })}
                            />
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
