import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Calendar } from 'lucide-react';
import { Input } from '../ui/Input';
import type { TherapyPlanEvent } from '../../types';
import type { TherapyPlanEventPayload } from '../../api/therapyPlans';

// ─── Draft type (used in edit mode) ──────────────────────────────────────────

export interface PlanEventDraft {
  /** Stable React key — client-side only, never sent to the API. */
  localId: string;
  /** "YYYY-MM-DDTHH:MM" format for datetime-local inputs. */
  startTime: string;
  endTime: string;
  title: string;
  isAvailable: boolean;
  order: number;
}

// ─── Helpers (exported for use in CreateTherapyPlan / EditTherapyPlan) ────────

const toDatetimeLocal = (iso?: string | null): string => {
  if (!iso) return '';
  return iso.slice(0, 16);
};

export const eventsToFormDrafts = (events: TherapyPlanEvent[]): PlanEventDraft[] =>
  [...events]
    .sort((a, b) => a.order - b.order)
    .map((e, idx) => ({
      localId: e.id,
      startTime: toDatetimeLocal(e.startTime),
      endTime: toDatetimeLocal(e.endTime),
      title: e.title ?? `Day ${idx + 1}`,
      isAvailable: e.isAvailable,
      order: idx,
    }));

export const draftsToApiPayload = (drafts: PlanEventDraft[]): TherapyPlanEventPayload[] =>
  drafts.map((d, idx) => ({
    startTime: new Date(d.startTime).toISOString(),
    endTime: d.endTime ? new Date(d.endTime).toISOString() : null,
    title: d.title.trim() || null,
    isAvailable: d.isAvailable,
    order: idx,
  }));

// ─── Auto-generation for WELLNESS_RETREAT ────────────────────────────────────

function autoGenerateDays(
  planStartTime: string,
  n: number,
  existing: PlanEventDraft[],
): PlanEventDraft[] {
  if (!planStartTime) return [];
  const base = new Date(planStartTime);
  if (isNaN(base.getTime())) return [];

  const baseTimeHHMM = planStartTime.slice(11, 16) || '09:00';

  return Array.from({ length: n }, (_, i) => {
    const d = new Date(base);
    d.setDate(d.getDate() + i);
    const datePrefix = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

    const existingDayDate = existing[i]?.startTime.slice(0, 10);
    const timeHHMM =
      existingDayDate === datePrefix
        ? existing[i].startTime.slice(11, 16) || baseTimeHHMM
        : baseTimeHHMM;

    const existingEndTime =
      existingDayDate === datePrefix ? existing[i].endTime : '';

    return {
      localId: existing[i]?.localId ?? `day-${i}-${Date.now()}-${Math.random()}`,
      startTime: `${datePrefix}T${timeHHMM}`,
      endTime: existingEndTime,
      title: `Day ${i + 1}`,
      isAvailable: true,
      order: i,
    };
  });
}

// ─── Props ────────────────────────────────────────────────────────────────────

interface ViewProps {
  mode: 'view';
  events: TherapyPlanEvent[];
  planType: string;
}

interface EditProps {
  mode: 'edit';
  drafts: PlanEventDraft[];
  planType: string;
  /** "YYYY-MM-DDTHH:MM" from the parent form — drives auto-generation for WELLNESS_RETREAT */
  planStartTime?: string;
  onChange: (drafts: PlanEventDraft[]) => void;
}

type PlanScheduleProps = ViewProps | EditProps;

// ─── Component ────────────────────────────────────────────────────────────────

export const PlanSchedule = (props: PlanScheduleProps) => {
  const { t } = useTranslation();

  // ── VIEW MODE ──────────────────────────────────────────────────────────────

  if (props.mode === 'view') {
    const { events } = props;
    if (!events || events.length === 0) return null;

    const sorted = [...events].sort((a, b) => a.order - b.order);

    return (
      <section className="mb-6">
        <h3 className="text-sm font-medium text-stone-500 uppercase tracking-wide mb-3">
          {t('therapyPlans.schedule.title', 'Schedule')}
        </h3>
        <div className="space-y-2">
          {sorted.map((evt) => (
            <div
              key={evt.id}
              className="flex items-start gap-3 rounded-lg p-3 border bg-stone-50 border-stone-100"
            >
              <Calendar className="h-4 w-4 text-teal-600 flex-shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-x-2 gap-y-0.5">
                  {evt.title && (
                    <span className="text-xs font-semibold text-stone-700 uppercase tracking-wide">
                      {evt.title}
                    </span>
                  )}
                  <span className="text-sm font-medium text-stone-800">
                    {new Date(evt.startTime).toLocaleString()}
                  </span>
                  {evt.endTime && (
                    <span className="text-xs text-stone-500">
                      — {new Date(evt.endTime).toLocaleString()}
                    </span>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>
    );
  }

  // ── EDIT MODE — only rendered for WELLNESS_RETREAT ────────────────────────

  if (props.planType !== 'WELLNESS_RETREAT') return null;

  return <WellnessRetreatSchedule {...props} t={t} />;
};

// ─── Separated retreat component (avoids Rules-of-Hooks violations) ───────────

const WellnessRetreatSchedule = ({
  drafts,
  onChange,
  planStartTime,
  t,
}: Omit<EditProps, 'mode' | 'planType'> & { t: ReturnType<typeof useTranslation>['t'] }) => {
  const [numDays, setNumDays] = useState<number>(Math.max(drafts.length, 1));

  useEffect(() => {
    if (!planStartTime) return;
    const generated = autoGenerateDays(planStartTime, numDays, drafts);
    if (generated.length > 0) {
      onChange(generated);
    }
    // We intentionally omit `drafts` from deps to avoid infinite loops —
    // we only want to re-generate when the anchor inputs change.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [planStartTime, numDays]);

  const updateDraft = (localId: string, patch: Partial<PlanEventDraft>) => {
    onChange(drafts.map((d) => (d.localId === localId ? { ...d, ...patch } : d)));
  };

  return (
    <div className="space-y-3">
      {/* Header + number-of-days control */}
      <div className="flex items-center justify-between">
        <p className="text-sm font-medium text-stone-700">
          {t('therapyPlans.schedule.title', 'Schedule')}
        </p>
        <div className="flex items-center gap-2">
          <label className="text-xs text-stone-500">
            {t('therapyPlans.schedule.numDays', 'Number of days')}
          </label>
          <input
            type="number"
            min={1}
            max={30}
            value={numDays}
            onChange={(e) => setNumDays(Math.max(1, parseInt(e.target.value) || 1))}
            className="w-16 rounded-md border border-stone-300 px-2 py-1 text-sm text-center focus:outline-none focus:ring-2 focus:ring-teal-500"
          />
        </div>
      </div>

      {!planStartTime && (
        <p className="text-sm text-stone-400 italic">
          {t('therapyPlans.schedule.setStartFirst', 'Set the plan start date above to generate the schedule.')}
        </p>
      )}

      {drafts.map((draft, idx) => (
        <div
          key={draft.localId}
          className="border border-stone-200 rounded-lg p-3 space-y-3 bg-stone-50"
        >
          <span className="text-xs font-semibold text-stone-600 uppercase tracking-wide">
            {draft.title || `Day ${idx + 1}`}
          </span>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <Input
              type="datetime-local"
              label={t('therapyPlans.form.startTime', 'Start Time')}
              value={draft.startTime}
              onChange={(e) => updateDraft(draft.localId, { startTime: e.target.value })}
            />
            <Input
              type="datetime-local"
              label={`${t('therapyPlans.form.endTime', 'End Time')} (${t('common.optional', 'optional')})`}
              value={draft.endTime}
              onChange={(e) => updateDraft(draft.localId, { endTime: e.target.value })}
            />
          </div>
        </div>
      ))}
    </div>
  );
};
